<h1><b>Numpy</b></h1>

An array is a grid of vlaues and i tconains informaiton about the raw data, how to locate an element, and how to interpret an element.

Numpy consumes less memory, which is fast as compared to the python list and is very convenient to use.

In [1]:
pip install numpy


[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:

import numpy as np

In [3]:
x=[1,2,3,4] #which is a list
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


<h1><b>The importance of NumPy in python</b></h1>

<ol>
<li>wide variety of mathematical operations on arrays.</li>
<li>it supplies and enormous library of high-level mathematical functions that operate on these arrays and matrices</li>
<Li>mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete FOurier transorms, basic linear algebra, basic staistical operation, random simulation and much more</li>
</ol>

##### l=[]
for i in range (1,5):
    x=input("Enter the value:")
    l.append(x)
print(np.array(l))


In [4]:
#two dimensional array
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(type(arr2))
print("the no. of dimension:\n")
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
the no. of dimension:

2


In [5]:
#three dimensional array
arr3=np.array([[[1,2,3,4],[3,4,5,6],[7,8,9,0]]])
print(arr3)
print("the no. of dimension:\n")
print(arr3.ndim)

[[[1 2 3 4]
  [3 4 5 6]
  [7 8 9 0]]]
the no. of dimension:

3


<h3>Zero</h3>


In [6]:
arr_zero=np.zeros(4)
print(arr_zero)

[0. 0. 0. 0.]


In [7]:
arr_zeros=np.zeros((2,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


<h3>Ones</h3>

In [8]:
arr_one=np.ones(4)
print(arr_one)

[1. 1. 1. 1.]


<h3>Empty</h3>


In [9]:
arr_empty=np.empty((4))
print(arr_empty)

[1. 1. 1. 1.]


<h3>Range</h3>

In [10]:
arr_range=np.arange(4)
print(arr_range)

[0 1 2 3]


<h3>Idenity Matrix</h3>

In [11]:
arr_diagonal=np.eye(3)
print(arr_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arr_diagonal=np.eye(3,5)
print(arr_diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


<h3>linspace</h3>


In [13]:
arr_space=np.linspace(0,10,num=5)
print(arr_space)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
arr_lin=np.linspace(1,4,num=4)
print(arr_lin)

[1. 2. 3. 4.]


In [15]:
arr_space=np.linspace(0,20,num=5)
print(arr_space)

[ 0.  5. 10. 15. 20.]


<h3>Arthematic operation</h3>


In [16]:
# np.add(a,b)
# np.substract(a,b)
# np.multiply(a,b)
# np.divide(a,b)
# np.mod(a,b)
# np.power(a,b)
# np.reciprocal(a)

In [17]:
x=np.array([2,3,4])
y=np.array([1,2,3])
add=np.add(x,y)
print(add)

[3 5 7]


In [18]:
ar=np.array([[2,3,4,5],[1,6,4,2]])
print(ar,"\n")

ar2=np.array([[3,4,5,6],[2,7,6,4]])
print(ar2,"\n")
addd=np.add(ar,ar2)#one way to add
print(addd)
print("\n \t")
var=ar+ar2#another way to add
print(var)

[[2 3 4 5]
 [1 6 4 2]] 

[[3 4 5 6]
 [2 7 6 4]] 

[[ 5  7  9 11]
 [ 3 13 10  6]]

 	
[[ 5  7  9 11]
 [ 3 13 10  6]]


In [19]:
ar=np.array([[2,3,4,5],[1,6,4,2]])
ar2=np.array([[3,4,5,6],[2,7,6,4]])
mul=np.multiply(ar,ar2)#one way to add
print(mul)


[[ 6 12 20 30]
 [ 2 42 24  8]]


In [20]:
print("min:",np.min(ar)," place of the min. value:",np.argmin(ar))
print("max:",np.max(ar)," place of the max. value:",np.argmax(ar))

min: 1  place of the min. value: 4
max: 6  place of the max. value: 5


In [21]:
print("min:",np.min(ar,axis=1))

min: [2 1]


In [22]:
print("min:",np.min(ar,axis=0))
#in term of column the minimum number in the column will be selected 

min: [1 3 4 2]


In [23]:
#finding the sq. root of the array
ar1=np.array([[1,16,4],[9,25,36]])
ar2=np.sqrt(ar1)
print(ar2)


[[1. 4. 2.]
 [3. 5. 6.]]


In [24]:

ar3=np.array([30,90,0,3.14,1.57])
ans=np.sin(ar3)#in radian
print(ans)

[-0.98803162  0.89399666  0.          0.00159265  0.99999968]


In [25]:
cumsum=np.array([2,3,4,5])
out=np.cumsum(cumsum)#algorithm=2,2+3,2+3+4,and likewise
print(out)


[ 2  5  9 14]


<h3>Shapes and Reshapes</h3>

In [26]:
#firt we taling about shape
variable=np.array([[1,2,3,4],[2,3,5,6]])
print(variable)
print("\n")
print("The shape of the variable:",variable.shape)


[[1 2 3 4]
 [2 3 5 6]]


The shape of the variable: (2, 4)


In [27]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print("the no. of dimension=",var1.ndim)
print("the shape of the variable:",var1.shape)#result=(1,1,1,4),here 4 column in that 4 dimension and 1,1,1 are the rows that was in that diff. dimension 

[[[[1 2 3 4]]]]
the no. of dimension= 4
the shape of the variable: (1, 1, 1, 4)


<h3>reshape</h3>

In [28]:
var2=np.array([1,2,3,4,7,4])
print("before the dimension was:",var2.ndim)
print(var2)
print()
resh=var2.reshape(2,3)#reshape(row,col) enter row,col i.e required
print(resh)

print("after reshaping the dim. is:",resh.ndim)

before the dimension was: 1
[1 2 3 4 7 4]

[[1 2 3]
 [4 7 4]]
after reshaping the dim. is: 2


In [29]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,12,11])
print(var3)
print()
newdim=var3.reshape(2,3,2)
print(newdim)
print("the dimension after reshaping:",newdim.ndim)
print()
onedim=newdim.reshape(-1)#after passing -1 we can reshape in 1d array
print(onedim)
print(onedim.ndim)
               

[ 1  2  3  4  5  6  7  8  9 10 12 11]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [12 11]]]
the dimension after reshaping: 3

[ 1  2  3  4  5  6  7  8  9 10 12 11]
1


<h3>Broadcasting</h3>

In [30]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3])
#print(var1+var2)  #while printing this we find the error 


In [31]:
ar1=np.array([1,2,3])
ar2=np.array([[1],[2],[3]])
print(ar1)
print(ar1.shape)
print()
print(ar2)
print(ar2.shape)
print()
print(ar1+ar2)


[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


<h3>Slicing</h3>


In [32]:
arr=np.array([1,2,3,4])
print(arr)
print()
print("after slicing the result is like this as shown below:")
print(arr[:3])


[1 2 3 4]

after slicing the result is like this as shown below:
[1 2 3]


In [33]:
#for the 2d, 3d slicing can be done in same ways
ar1=np.array([[1,2,3,4,6],[2,3,4,5,6],[8,7,6,5,3],[2,3,4,5,6]])
print(ar1)
print()
print(ar1[0:3:2,0:5:2])
#array[row,column]


[[1 2 3 4 6]
 [2 3 4 5 6]
 [8 7 6 5 3]
 [2 3 4 5 6]]

[[1 3 6]
 [8 6 3]]


In [34]:
ar3=np.array([[[1,2,3,4],[2,3,4,5],[4,5,6,7],[6,7,8,9]]])
print(ar3)

[[[1 2 3 4]
  [2 3 4 5]
  [4 5 6 7]
  [6 7 8 9]]]


<h3>Iteration</h3>

In [35]:
variable=np.array([1,2,3,4,5,6])
print(variable)
print()
for i in variable:
    print(i)

[1 2 3 4 5 6]

1
2
3
4
5
6


In [36]:
var=np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(var)
print()
for i in var:
    for j in i:
        print(j)
    print()

[[1 2 3 4 5]
 [3 4 5 6 7]]

1
2
3
4
5

3
4
5
6
7



In [37]:
var=np.array([[[1,2,3,4,5],[3,4,5,6,7]]])
print(var)
print()
for i in var:
    for j in i:
        for k in j:
            print(k)
    print()

[[[1 2 3 4 5]
  [3 4 5 6 7]]]

1
2
3
4
5
3
4
5
6
7



In [38]:
#nditer function

var=np.array([[[1,2,3,4,5],[3,4,5,6,7]]])
for i in np.nditer(var):
    print(i)

1
2
3
4
5
3
4
5
6
7


In [39]:

var=np.array([[[1,2,3,4,5],[3,4,5,6,7]]])
for i in np.nditer(var,flags=['buffered'],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'3'
b'4'
b'5'
b'6'
b'7'


In [40]:

var=np.array([[[1,2,3,4,5],[3,4,5,6,7]]])
for i,d in np.ndenumerate(var):
    print(i,d) #this prints the both index and value in array

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(0, 1, 3) 6
(0, 1, 4) 7


<h3>Copy and View</h3>

In [41]:
co=np.array([2,3,4,5,6])
copy=co.copy()#array has been copied as a new variable and has its own data
co[2]=50#this will not affect the copied array
print(co)
print()
print(copy)

[ 2  3 50  5  6]

[2 3 4 5 6]


In [42]:
vi=np.array([8,5,7,2,1])
view=vi.view()#this access from the real variable and it doesn't have its own data
vi[2]=30#since the veiw function access from the original data so it changes on both vairable
print(vi)
print()
print(view)

[ 8  5 30  2  1]

[ 8  5 30  2  1]


<h3>Joining & Split NumPY Arrays</h3>

In [43]:
var=np.array([1,2,3,4])
var2=np.array([5,6,7,8])
con=np.concatenate((var,var2))
print(con)

[1 2 3 4 5 6 7 8]


In [44]:
var=np.array([[1,2,3],[3,2,1]])
var2=np.array([[5,6,7],[5,4,3]])
con=np.concatenate((var,var2),axis=1)
print(con)
print()
con_x=np.concatenate((var,var2),axis=0)
print(con_x)

[[1 2 3 5 6 7]
 [3 2 1 5 4 3]]

[[1 2 3]
 [3 2 1]
 [5 6 7]
 [5 4 3]]


In [45]:
var=np.array([1,2,3,4])
var2=np.array([5,6,7,8])
stack=np.stack((var,var2))
print(stack)
print()
stack2=np.stack((var,var2),axis=1)
print(stack)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [46]:
stack_row=np.hstack((var,var2))
print(stack_row)

[1 2 3 4 5 6 7 8]


In [47]:
stack_column=np.vstack((var,var2))
print(stack_column)

[[1 2 3 4]
 [5 6 7 8]]


In [48]:
stack_height=np.dstack((var,var2))
print(stack_height)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


<h4>split array</h4>

In [49]:
var=np.array([4,5,6,7,8])
print(var)
print()
spl=np.array_split(var,3)
print(spl)
print(type(spl))
print()
print(spl[0])


[4 5 6 7 8]

[array([4, 5]), array([6, 7]), array([8])]
<class 'list'>

[4 5]


In [50]:
var2d=np.array([[1,2,4],[2,3,4],[6,7,8],[4,5,2]])
print(var2d)
print()
splt_var=np.array_split(var2d,2)
splt_var3=np.array_split(var2d,3)
print()
print(splt_var)
print()
print(splt_var3)


[[1 2 4]
 [2 3 4]
 [6 7 8]
 [4 5 2]]


[array([[1, 2, 4],
       [2, 3, 4]]), array([[6, 7, 8],
       [4, 5, 2]])]

[array([[1, 2, 4],
       [2, 3, 4]]), array([[6, 7, 8]]), array([[4, 5, 2]])]


<h3>Search</h3>


In [51]:
var=np.array([1,2,3,4,5,6,7,5,4,3,9,2,7,9])
x=np.where(var==7)
print(x)
print()
x_by_two=np.where((var%2)==0)
print("the elements of array being divisible by 2 positions are:")
print(x_by_two)

(array([ 6, 12], dtype=int64),)

the elements of array being divisible by 2 positions are:
(array([ 1,  3,  5,  8, 11], dtype=int64),)


In [52]:
#seach sorted function
var1=np.array([1,2,3,4,5,8,9])
x=np.searchsorted(var1,6,side="right")
print(x)

5


In [53]:
var1=np.array([1,2,3,4,5,8,9])
x=np.searchsorted(var1,[6,7],side="right")
print(x)

[5 5]


<h3>SORT</h3>


In [54]:
var=np.array([4,2,7,5,2,1,9,22,11])
print(np.sort(var))

[ 1  2  2  4  5  7  9 11 22]


In [55]:
var=np.array(['s','a','e','d'])
print(np.sort(var))

['a' 'd' 'e' 's']


In [56]:
var=np.array([[4,2,7],[5,2,1],[9,22,11],[34,23,56],[45,76,56]])
print(np.sort(var))

[[ 2  4  7]
 [ 1  2  5]
 [ 9 11 22]
 [23 34 56]
 [45 56 76]]


In [57]:
#filter array
var_3=np.array([2,3,6,55])
fltr=[True,False,False,True]
new_a=var_3[fltr]
print(new_a)

[ 2 55]


In [58]:
#array shuffle
var=np.array([3,6,2,4,7])
np.random.shuffle(var)
print(var)

[2 3 6 4 7]


In [59]:
#unique
var=np.array([3,6,2,4,7,4,9,1,2,3,9])
x=np.unique(var,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 6, 7, 9]), array([7, 2, 0, 3, 1, 4, 6], dtype=int64), array([1, 2, 2, 2, 1, 1, 2], dtype=int64))


In [60]:
var2=np.array([2,4,1,5,7,7,9])
y=np.resize(var2,(2,3))
print(y)

[[2 4 1]
 [5 7 7]]


Arithemtic Functions 
order:{'C','F','A','K'}, optional
'C' means to flatten in row-major (C-style) order
'F' means to flatten in column-major (FOrtran-style) order.
'A' means to flatten in column-major order if 'a' is Fortran *contigous* in memory,row-major order othrerwise
'K' means to flatten 'a' in the ordder the elements occur in memory 
the default is 'C'


In [61]:
var2=np.array([2,4,1,5,7,7,9])
y=np.resize(var2,(2,3))
print(y)
print()
print(y.flatten('c'))
print()
print(y.flatten('F'))
print()
print("Ravel:",np.ravel(y))
print()
print("Ravel:",np.ravel(y,order='f'))

[[2 4 1]
 [5 7 7]]

[2 4 1 5 7 7]

[2 5 4 7 1 7]

Ravel: [2 4 1 5 7 7]

Ravel: [2 5 4 7 1 7]


<h3>Insert</h3>

In [62]:
var=np.array([2,3,4,5,6])
v=np.insert(var,1,20)
print(v)


[ 2 20  3  4  5  6]


In [63]:
var=np.array([2,3,4,5,6])
v=np.insert(var,(1,4),20)
print(v)

[ 2 20  3  4  5 20  6]


In [64]:
var=np.array([[1,2,3],[4,5,6]])
print(var)
print()

var1=np.insert(var,2,4,axis=1)
print(var1)
print()
var1=np.insert(var,2,4)
print(var1)
print()
var1=np.insert(var,2,4,axis=0)
print(var1)
print()
var1=np.insert(var,2,(4,7,8),axis=0)
print(var1)

[[1 2 3]
 [4 5 6]]

[[1 2 4 3]
 [4 5 4 6]]

[1 2 4 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [4 4 4]]

[[1 2 3]
 [4 5 6]
 [4 7 8]]


In [65]:
#append
print("append function")
print()
var=np.array([3,4,1,5,6])
print(np.append(var,4))
print()
print(np.append(var,5.4))

append function

[3 4 1 5 6 4]

[3.  4.  1.  5.  6.  5.4]


In [67]:
var=np.array([[3,4,5],[6,5,1]])
print(var)
print()
var_append=np.append(var,4)
print(var_append)
print()
var_append=np.append(var,[[4,5,6]],axis=0)
print(var_append)
print()


[[3 4 5]
 [6 5 1]]

[3 4 5 6 5 1 4]

[[3 4 5]
 [6 5 1]
 [4 5 6]]



<h2>MATRIX</h2>

In [70]:
var=np.array([[1,2,3],[4,5,6]])
print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [71]:
var=np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var))

#there output looks same but its types are different as it's shown there

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [88]:
var=np.matrix([[1,2],[3,4]])
var2=np.matrix([[5,6,7],[2,3,4]])
print("var:")
print(var)
print()
print("var2:")
print(var2)
print()
var3=var*var2
print(var3)
print("likewise we can also do the same operation by using dot operation")
print(var.dot(var2))

var:
[[1 2]
 [3 4]]

var2:
[[5 6 7]
 [2 3 4]]

[[ 9 12 15]
 [23 30 37]]
likewise we can also do the same operation by using dot operation
[[ 9 12 15]
 [23 30 37]]


In [92]:
var=np.matrix([[1,2,3],[3,4,5]])
print(var)
print()
print("after transposing the matrix:")
print(np.transpose(var))
print()
print("or else we can also transpose like this:")
print(var.T)

[[1 2 3]
 [3 4 5]]

after transposing the matrix:
[[1 3]
 [2 4]
 [3 5]]

or else we can also transpose like this:
[[1 3]
 [2 4]
 [3 5]]


In [103]:
var2=np.matrix([[5,6,7],[2,3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[5 6 7]
 [2 3 4]]

[[5 2]
 [6 3]
 [7 4]]


In [107]:
var=np.array([[1,2],[3,4]])
print(var)
print("we need to go through linear algebras inverse function soo linalg.inv function is used")
print(np.linalg.inv(var))

[[1 2]
 [3 4]]
we need to go through linear algebras inverse function soo linalg.inv function is used
[[-2.   1. ]
 [ 1.5 -0.5]]


In [116]:
var=np.array([[1,2],[3,4]])
print(var)
print()
print(np.dot(var,var))
print()
print(np.linalg.matrix_power(var,2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]


In [117]:
var=np.array([[1,2],[3,4]])
print(var)
print()

print(np.linalg.matrix_power(var,0))

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]


In [119]:
print(np.linalg.matrix_power(var,-1))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [121]:
print(np.linalg.det(var))

-2.0000000000000004


In [122]:
var=np.array([[[1,2,3],[3,4,3],[1,2,3]]])
print(var)
print()
print(np.linalg.det(var))

[[[1 2 3]
  [3 4 3]
  [1 2 3]]]

[0.]
